// Re-export schema from api to ensure consistency
export {
  verifiabilityLabelEnum,
  sourceTypeEnum,
  claimTypeEnum,
  claimStatusEnum,
  evidenceStanceEnum,
  eventTypeEnum,
  thumbnailSourceEnum,
  sources,
  items,
  stories,
  storyItems,
  claims,
  evidence,
  storyEvents,
  sourcesRelations,
  itemsRelations,
  storiesRelations,
  storyItemsRelations,
  claimsRelations,
  evidenceRelations,
  storyEventsRelations,
  type Source,
  type NewSource,
  type Item,
  type NewItem,
  type Story,
  type NewStory,
  type StoryItem,
  type NewStoryItem,
  type Claim,
  type NewClaim,
  type Evidence,
  type NewEvidence,
  type StoryEvent,
  type NewStoryEvent,
} from '../../api/src/database/schema';
