// Re-export schema from API to ensure consistency
// In production, consider moving shared schema to @rafineri/shared package

export {
  verifiabilityLabelEnum,
  sourceTypeEnum,
  claimTypeEnum,
  claimStatusEnum,
  evidenceStanceEnum,
  eventTypeEnum,
  thumbnailSourceEnum,
  thumbnailRefreshJobStatusEnum,
  sources,
  items,
  stories,
  storyItems,
  claims,
  evidence,
  storyEvents,
  thumbnailRefreshJobs,
  sourcesRelations,
  itemsRelations,
  storiesRelations,
  storyItemsRelations,
  claimsRelations,
  evidenceRelations,
  storyEventsRelations,
  thumbnailRefreshJobsRelations,
  type Source,
  type NewSource,
  type Item,
  type NewItem,
  type Story,
  type NewStory,
  type StoryItem,
  type NewStoryItem,
  type Claim,
  type NewClaim,
  type Evidence,
  type NewEvidence,
  type StoryEvent,
  type NewStoryEvent,
  type ThumbnailRefreshJob,
  type NewThumbnailRefreshJob,
} from '../../api/src/database/schema';
